bl/urls.py
from django.urls import path, include
from . import views
from django.conf.urls import url


app_name = 'bl'

urlpatterns = [
    path('', views.index, name="index"),
    path('submitRegister', views.submitRegister, name="submitRegister"),
    path('pending', views.pending, name="pending"),
    path('dashboard', views.dashboard, name="dashboard"),
    path('addsong', views.addsong, name="addsong"),
    path('addsongpage', views.addsongpage, name="addsongpage"),
    path('songdetail/<slug:id>', views.songdetail, name="songdetail"),
    path('uploads', views.uploads, name="uploads"),
    path('uploadtype', views.uploadtype, name="uploadtype"),
    path('uploadtrack', views.uploadtrack, name="uploadtrack"),
     path('submitAlbumDetail', views.submitAlbumDetail, name="submitAlbumDetail"),
    
    path('uploadalbum', views.uploadalbum, name="uploadalbum"),
    path('uploaddetail/<slug:id>', views.uploaddetail, name="uploaddetail"),


    

    path('index', views.index, name="index"),

    path('login', views.login, name="login"),

    path('registerbasicinfo', views.registerbasicinfo, name="registerbasicinfo"),

    path('changemailredirect', views.changemailredirect, name="changemailredirect"),

    path('loginredirect', views.loginredirect, name="loginredirect"),


    path('thanks', views.thanks, name="thanks"),

    path('mypod', views.mypod, name="mypod"),


    path('gettags', views.gettags, name="gettags"),

    path('uploadtag', views.uploadtag, name="uploadtag"),

    path('editUpload/<slug:track_id>', views.editUpload, name="editUpload"),
    path('editUploads', views.editUploads, name="editUploads"),

    path('editsong', views.editsong, name="editsong"),


path('editsongUpload', views.editsongUpload, name="editsongUpload"),




    path('myUploads', views.myUploads, name="myUploads"),



    



        path('register_view', views.register_view, name="register_view"),
    path('is_email_valid', views.is_email_valid, name="is_email_valid"),
                path('is_password_valid', views.is_password_valid, name="is_password_valid"),
                    path('is_username_valid', views.is_username_valid, name="is_username_valid"),



















    # SUDOURLS
    path('sudodashboard', views.sudodashboard, name="sudodashboard"),
    path('users', views.users, name="users"),
    path('userdetail/<slug:id>', views.userdetail, name="userdetail"),

    path('approvecreator/<slug:id>', views.approvecreator, name="approvecreator"),









    # path('expertDetail/<slug:id>', views.expertDetail , name="expertDetail"),
    # path('deleteExpert/<slug:id>', views.deleteExpert , name="deleteExpert"),
    path('register', views.register, name="register"),
    path('logout', views.logout, name="logout"),
    path('completeregister', views.completeregister, name="completeregister"),



    path('upload', views.upload, name="upload"),
    # url('oauth', include('social_django.urls', namespace='social')),

]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from rest_framework.routers import DefaultRouter
from django.conf.urls import url
router = DefaultRouter() 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('bl.urls')),
    path('rf', include(router.urls)),
    path('api/', include('api.urls')),
    path('doc/', include('rest_framework_docs.urls')),
    url('oauth', include('social_django.urls', namespace='social')),
     url(r'^notifications/', include('notify.urls', 'notifications')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bl/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from . models import *

from django.forms import ModelChoiceField,ModelForm,TextInput,Textarea


from django.db import transaction

from django.utils.translation import ugettext_lazy as _
import datetime


class FileFieldForm(forms.Form):
    ffile = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(max_length=30,
        widget=forms.TextInput(attrs={'class' : 'form-control','autocomplete':'off'}))
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'class' : 'form-control'}))
    first_name = forms.CharField(max_length=30,
        widget=forms.TextInput(attrs={'class' : 'form-control','autocomplete':'off'}))
    last_name = forms.CharField(max_length=30,
        widget=forms.TextInput(attrs={'class' : 'form-control','autocomplete':'off'}))
    phone = forms.CharField(max_length=30,
        widget=forms.TextInput(attrs={'class' : 'form-control','autocomplete':'off'})) 
    password1 = forms.CharField(max_length=30,
        widget=forms.TextInput(attrs={'class' : 'form-control','type' : 'password',}))   
    password2 = forms.CharField(max_length=30,
        widget=forms.TextInput(attrs={'class' : 'form-control','type' : 'password',}))  


    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('first_name','last_name','email','username')
        
    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        self.fields['email'].label = "Email Address"
        self.fields['password1'].label = "Password"
        self.fields['password2'].label = "Re-Type Password"
        self.fields['dob'].label = "Date of Birth"

    @transaction.atomic    
    def save(self):        
        user = super().save(commit=False)
        user.is_doctor = True
        

        user.save()    
        


        # user.role.set(range(Role.DOCTOR))     
        doctor = Doctor.objects.create(user=user)  
        Employee.objects.create(user=user)  
        # doctor.departmentname.add(*self.get('departmentname'))    
        # doctor.usericon.add(*self.get('usericon'))    
            
        return doctor

bl/views.py
from django.shortcuts import render,reverse,redirect,get_object_or_404
from django.http import HttpResponseRedirect
from . models import *
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from pyrebase import pyrebase
from django.contrib import auth
import re
from django.conf import settings
from django.urls import resolve
from django.http import JsonResponse
import sys
from django.core.files.base import ContentFile

from django.core.validators import validate_email
from django.core.exceptions import ValidationError
from django.conf import settings
import re



import base64

# Create your views here.

from tinytag import TinyTag
from notify.signals import notify
from django.contrib.auth.models import User


from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.template.loader import render_to_string
import requests


from .tokens import account_activation_token


config = {
    'apiKey': "AIzaSyANXTxEpF-3zzufKftR3_6AzhLXYh0tq6A",
    'authDomain': "pod-music-eb445.firebaseapp.com",
    'databaseURL':  "https://pod-music-eb445.firebaseio.com",
    'projectId': "pod-music-eb445",
    'storageBucket': "pod-music-eb445.appspot.com",
    'messagingSenderId': "866068650147",
    'appId' : "1:866068650147:web:3457f5499557ec4c"
 
}


firebase = pyrebase.initialize_app(config)
authe = firebase.auth()
db = firebase.database()



def logout(request):
    auth.logout(request)
    # if request.user.is_authenticated:
    #     auth.logout(request)
    # messages.add_message(request, messages.INFO,
    #                      'You are Successfully Logged Out')
    # messages.add_message(request, messages.INFO, 'Thanks for visiting.')
    return HttpResponseRedirect(reverse('bl:index'))

def login(request):
    return render(request,"bl/auth/login.html")


# @login_required
# def home(request):
    # print(request.user)
    
    # get_object_or_404(Creator, email=request.user.email)


    # try:
    #     if request.user.is_authenticated:
    #         creator = Creator.objects.get(email=request.user.email)
    #         if creator.status == 'pending_approval':
    #             return HttpResponseRedirect(reverse('bl:pending'))
    #             # return render(request,"bl/pending.html")
            
    #         elif creator.status == 'approved':
    #             return HttpResponseRedirect(reverse('bl:dashboard'))
    #             # return render(request,"bl/dashboard.html")

    #         else:
    #             return HttpResponseRedirect(reverse('bl:completeregister'))
    #     else:
    #         creator = None
    #         return HttpResponseRedirect(reverse('bl:index'))

    # except Creator.DoesNotExist:
    #     creator = None
    #     return HttpResponseRedirect(reverse('bl:index'))



    

def loginredirect(request):
    try:

        creator = Creator.objects.get(email=request.user.email)
        if creator.status == 'pending_approval':
            return HttpResponseRedirect(reverse('bl:pending'))
            # return render(request,"bl/pending.html")

        elif creator.status == 'inactive':
            return HttpResponseRedirect(reverse('bl:dashboard'))
            # return render(request,"bl/dashboard.html")
        elif creator.status == 'approved':
            return HttpResponseRedirect(reverse('bl:dashboard'))
            # return render(request,"bl/dashboard.html")

        elif creator.status == 'super_creator':
            return HttpResponseRedirect(reverse('bl:sudodashboard'))
        elif request.user.is_staff:
            return HttpResponseRedirect(reverse('bl:sudodashboard'))
            # return render(request,"bl/dashboard.html")
        else:
            return HttpResponseRedirect(reverse('bl:dashboard'))
            # return render(request,"bl/dashboard.html")






    except Creator.DoesNotExist:
        return HttpResponseRedirect(reverse('bl:registerbasicinfo'))

    return render(request,"bl/changemailredirect.html")



    # if creator is None:
    #     # creator = Creator(email=request.user.email,status="pending_approval")
    #     creator = Creator(email=request.user.email)
    #     creator.save()
    #     # messages.success(request, ' Your changes were successfully saved')

    #     return HttpResponseRedirect(reverse('bl:completeregister'))
    #     # return render(request,"bl/register-complete.html")



    


    





def changemailredirect(request):
    auth.logout(request)
    return render(request,"bl/registerX.html")  
    # return render(request,"bl/changemailredirect.html")

def registerbasicinfo(request):

    return render(request,"bl/auth/register-form.html")


# @login_required
def index(request):
    try:
        if not request.user.is_anonymous:
            
            creator = Creator.objects.get(email=request.user.email)
            if creator.status == 'pending_approval':
                # return HttpResponseRedirect(reverse('bl:pending'))
                return HttpResponseRedirect(reverse('bl:dashboard'))

            elif creator.status == 'inactive':
                return HttpResponseRedirect(reverse('bl:dashboard'))
                # return render(request,"bl/dashboard.html")
            elif creator.status == 'approved':
                return HttpResponseRedirect(reverse('bl:dashboard'))
                # return render(request,"bl/dashboard.html")

            elif creator.status == 'super_creator':
                return HttpResponseRedirect(reverse('bl:sudodashboard'))
            elif request.user.is_staff:
                return HttpResponseRedirect(reverse('bl:sudodashboard'))
                # return render(request,"bl/dashboard.html")
            else:
                return HttpResponseRedirect(reverse('bl:dashboard'))
                # return render(request,"bl/dashboard.html")

        else:
            return render(request,"bl/home.html")




    except Creator.DoesNotExist:
        return HttpResponseRedirect(reverse('bl:registerbasicinfo'))
        # return render(request,"bl/home.html")

def dashboard(request):
    creator = Creator.objects.get(username=request.user.username)
    context = {
        'creator': creator,
        'a' : 'active' 
    }

    # kwargs={'id1': request.POST.get('courseid'),
    # return HttpResponseRedirect(reverse('bl:completeregister'))
    return render(request,"bl/creator/dashboard.html",context)








def uploadtype(request):
    context = {
        'c' : 'active' 
    }

    return render(request,"bl/creator/upload-type.html",context)

def uploadtrack(request):
    context = {
        'c' : 'active' 
    }

    return render(request,"bl/creator/upload-track.html",context)

def uploadalbum(request):
    context = {
        'c' : 'active' 
    }

    return render(request,"bl/creator/upload-album-detail.html",context)







def sudodashboard(request):

    return render(request,"bl/admin/dashboard.html")

def users(request):
    creators = Creator.objects.all()
    context = {
        'creators': creators
    }
    print('Image Dta:  %s.' % creators)
    return render(request,"bl/admin/users.html",context)

def userdetail(request,id):
    creator = Creator.objects.get(pk=id)
    context = {
        'creator': creator
    }

    return render(request,"bl/admin/user-detail.html",context)

def approvecreator(request,id):
    creator = Creator.objects.get(pk=id)
    creator.status = "approved"
    creator.save()
    context = {
        'creator': creator
    }

    user = User.objects.get(username=creator.username)

    notify.send(request.user, recipient=user, actor=request.user, verb='Welcome to Pod for Creators', nf_type='followed_by_one_user')

    return HttpResponseRedirect(reverse('bl:userdetail', kwargs={'id':creator.id}))

    # return render(request,"bl/admin/user-detail.html",context)


def register(request):
    if request.user.is_authenticated:
        try:

            creator = Creator.objects.get(email=request.user.email)
            if creator.status == 'pending_approval':
                return HttpResponseRedirect(reverse('bl:pending'))
                # return render(request,"bl/pending.html")

            elif creator.status == 'inactive':
                return HttpResponseRedirect(reverse('bl:dashboard'))
                # return render(request,"bl/dashboard.html")
            elif creator.status == 'approved':
                return HttpResponseRedirect(reverse('bl:dashboard'))
                # return render(request,"bl/dashboard.html")

            elif creator.status == 'super_creator':
                return HttpResponseRedirect(reverse('bl:sudodashboard'))
                # return render(request,"bl/dashboard.html")
            else:
                return HttpResponseRedirect(reverse('bl:dashboard'))
                # return render(request,"bl/dashboard.html")







        except Creator.DoesNotExist:
           
            return HttpResponseRedirect(reverse('bl:registerbasicinfo'))
    else:
        return render(request,"bl/register.html")

def pending(request):

    return render(request,"bl/pending.html")

def uploads(request):
    myuploads = Track.objects.filter(uploaded_by=Creator.objects.get(username=request.user.username))
    myalbums = Album.objects.filter(uploaded_by=Creator.objects.get(username=request.user.username))
    print("hhh")
    print(myuploads)
    context = {
        'myuploads': myuploads,
        'myalbums':myalbums,
        'd' : 'active' 
    }
    return render(request,"bl/creator/uploads.html",context)





def uploaddetail(request,id):
    song = Track.objects.get(pk=id)
    # song_file = Upload.objects.get(upload_id=song.track_file)
    context = {
        'song': song,
         'd' : 'active' 
        # 'song_file':song_file
    }

  

bl/templates/bl/creator/dashboard.html
{% extends "bl/creator/base.html" %}

{% load mytags %}


{% block head %}


 <!-- BEGIN: Page CSS-->
    <link rel="stylesheet" type="text/css" href="/static/bl/app-assets/css/core/menu/menu-types/vertical-menu.min.css">
    <link rel="stylesheet" type="text/css" href="/static/bl/app-assets/css/pages/dashboard-analytics.min.css">
     <link rel="stylesheet" type="text/css" href="/static/bl/app-assets/vendors/css/charts/apexcharts.css">
    <!-- END: Page CSS-->

{% endblock head %}

{% block content %}


<section id="dashboard-analytics">

  <div class="row">
    <!-- Activity Card Starts-->
    <div class="col-xl-3 col-md-6 col-12 activity-card">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title">Insight</h4>
        </div>
        <div class="card-content">
          <div class="card-body pt-1">
            <div class="d-flex activity-content">
              <div class="avatar bg-rgba-primary m-0 mr-75">
                <div class="avatar-content">
                  <i class="bx bx-bar-chart-alt-2 text-primary"></i>
                </div>
              </div>
              <div class="activity-progress flex-grow-1">
                <small class="text-muted d-inline-block mb-50">Followers</small>
                <small class="float-right">0</small>
                <div class="progress progress-bar-primary progress-sm">
                  <div class="progress-bar" role="progressbar" aria-valuenow="100" style="width:100%"></div>
                </div>
              </div>
            </div>
            <div class="d-flex activity-content">
              <div class="avatar bg-rgba-success m-0 mr-75">
                <div class="avatar-content">
                  <i class="bx bx-dollar text-success"></i>
                </div>
              </div>
              <div class="activity-progress flex-grow-1">
                <small class="text-muted d-inline-block mb-50">Uploads</small>
                <small class="float-right">{% getUploadCount %}</small>
                <div class="progress progress-bar-success progress-sm">
                  <div class="progress-bar" role="progressbar" aria-valuenow="100" style="width:100%"></div>
                </div>
              </div>
            </div>
            <div class="d-flex activity-content">
              <div class="avatar bg-rgba-warning m-0 mr-75">
                <div class="avatar-content">
                  <i class="bx bx-stats text-warning"></i>
                </div>
              </div>
              <div class="activity-progress flex-grow-1">
                <small class="text-muted d-inline-block mb-50">Streams</small>
                <small class="float-right">0</small>
                <div class="progress progress-bar-warning progress-sm">
                  <div class="progress-bar" role="progressbar" aria-valuenow="100" style="width:100%"></div>
                </div>
              </div>
            </div>
            <div class="d-flex mb-75">
              <div class="avatar bg-rgba-danger m-0 mr-75">
                <div class="avatar-content">
                  <i class="bx bx-check text-danger"></i>
                </div>
              </div>
              <div class="activity-progress flex-grow-1">
                <small class="text-muted d-inline-block mb-50">Featured Playlists</small>
                <small class="float-right">0</small>
                <div class="progress progress-bar-danger progress-sm">
                  <div class="progress-bar" role="progressbar" aria-valuenow="100" style="width:100%"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  


    <div class="col-lg-8 col-md-12">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title">Stream Details</h4>
        </div>
        <div class="card-content">
          <div class="card-body">
            <div id="line-chart"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% comment %} <div class="row">
    <!-- Task Card Starts -->
  
       <!-- Bar Chart -->
    <div class="col-lg-10 col-md-12">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title">Countries</h4>
        </div>
        <div class="card-content">
          <div class="card-body">
            <div id="bar-chart"></div>
          </div>
        </div>
      </div>
    </div>

    </div>
   
  </div> {% endcomment %}
</section>


 {% endblock content %}


{% block scripts %}


  <!-- BEGIN: Page Vendor JS-->
    <script src="/static/bl/app-assets/vendors/js/charts/apexcharts.min.js"></script>
    <script src="/static/bl/app-assets/vendors/js/extensions/dragula.min.js"></script>
    <!-- END: Page Vendor JS-->


    <!-- BEGIN: Page JS-->
    <script src="/static/bl/app-assets/js/scripts/pages/dashboard-analytics.min.js"></script>
     <script src="/static/bl/app-assets/js/scripts/charts/chart-apex.min.js"></script>
    <!-- END: Page JS-->

{% endblock scripts %}

bl/templates/bl/creator/upload-type.html
{% extends "bl/creator/base.html" %}

{% load mytags %}


{% block head %}





{% endblock head %}

{% block content %}

<section id="widgets-advance">
  <div class="row">
    <div class="col-12 mt-1 mb-2">
      <h4 style="text-align: center;">Go ahead select what you need to upload</h4>
   
    </div>
  </div>


<div class="row widgets-text-chart">


    <!-- User Widget with Image-top Starts -->
    <div class="col-xl-6 col-md-6 img-top-card">
    <a href={% url 'bl:uploadtrack' %}>
    
    
  
      <div class="card widget-img-top">
        <div class="card-content">
      <div class="text-center">

       <i style="font-size: 10rem" data-icon="music"  class="menu-livicon"></i>

</div>
        
          <div class="text-center">
            <h4>Tracks</h4>
         
          </div>
        </div>
   
      </div>

        </a>
    </div>
    <!-- User Widget with Image-top Ends -->



      <!-- User Widget with Image-top Starts -->
    {% comment %} <div class="col-xl-4 col-md-6 img-top-card">
      <a href={% url 'bl:uploadalbum' %}>
      <div class="card widget-img-top">
        <div class="card-content">
       <div class="text-center">

             <i style="font-size: 10rem" data-icon="morph-stack"  class="menu-livicon"></i>

</div>
          <div class="text-center">
            <h4>Album / EP</h4>
           
          </div>
        </div>
    
      </div>
         </a>
    </div> {% endcomment %}
    <!-- User Widget with Image-top Ends -->
      <!-- User Widget with Image-top Starts -->
    <div class="col-xl-6 col-md-6 img-top-card">
    <a href="#">
      <div class="card widget-img-top">
        <div class="card-content">
        <div class="text-center">

            <i style="font-size: 10rem" data-icon="headphones"  class="menu-livicon"></i>

</div>
          <div class="text-center">
            <h4>Podcast</h4>
          
          </div>
        </div>
       
      </div>
         </a>
    </div>
    <!-- User Widget with Image-top Ends -->

</div>

</section>  
{% endblock content %}

bl/templates/bl/creator/uploads.html
{% extends "bl/creator/base.html" %}








{% block head %}




{% endblock head %}

{% block content %}




<section id="basic-tabs-components">
    <div class="card">
        <div class="card-header">
            <div class="card-title">
                <h4>My Media</h4>
            </div>
        </div>
        <div class="card-content">
            <div class="card-body">
                <p>Browse through all your <code>Pod</code> media.</p>
                <ul class="nav nav-tabs" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" id="tracks-tab" data-toggle="tab" href="#tracks"
                            aria-controls="tracks" role="tab" aria-selected="true">
                            <i class="bx bx-home align-middle"></i>
                            <span class="align-middle">Tracks</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="albums-tab" data-toggle="tab" href="#albums" aria-controls="albums"
                            role="tab" aria-selected="false">
                            <i class="bx bx-user align-middle"></i>
                            <span class="align-middle">Albums</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="podcast-tab" data-toggle="tab" href="#podcast" aria-controls="podcast"
                            role="tab" aria-selected="false">
                            <i class="bx bx-message-square align-middle"></i>
                            <span class="align-middle">Podcasts</span>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" id="lyrics-tab" data-toggle="tab" href="#lyrics" aria-controls="lyrics"
                            role="tab" aria-selected="false">
                            <i class="bx bx-message-square align-middle"></i>
                            <span class="align-middle">Lyrics</span>
                        </a>
                    </li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane active" id="tracks" aria-labelledby="tracks-tab" role="tabpanel">
 <!-- datatable start -->
 <div class="table-responsive">
    {% if myuploads %}
    <table id="table-extended-chechbox" class="table table-transparent">

        <thead>
            <tr>
                <th></th>
                <th class="pl-0">name</th>
                <th>date added</th>
                <th>duration</th>

            </tr>
        </thead>
        <tbody>

            {% for upload in myuploads  %}

            <tr>
                <td></td>


                {% if upload.cover %}
                <td class="text-bold-600 pl-0"><img src="{{upload.cover}}" alt="file" class="mr-1" height="36"
                        width="36">
                    <a href={% url 'bl:uploaddetail' upload.track_id %} >{{upload.title}}</a>
                
                </td>
                {% else %}

                <td class="text-bold-600 pl-0"><img src="/static/bl/app-assets/images/album.png" alt="file"
                        class="mr-1" height="36" width="36">
                     <a href={% url 'bl:uploaddetail' upload.track_id %} >{{upload.title}}</a>
                    
                </td>
                {% endif %}




                <td>{{upload.created_at}}</td>
                <td>{{upload.duration}}</td>
                {% comment %} <td>--:--</td> {% endcomment %}
                <td>
                    <div class="dropdown">
                        <span
                            class="bx bx-dots-horizontal-rounded font-medium-3 dropdown-toggle nav-hide-arrow cursor-pointer"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" role="menu">
                        </span>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a class="dropdown-item" href="#"><i class="bx bx-edit-alt mr-1"></i> edit</a>
                            <a class="dropdown-item" href="#"><i class="bx bx-trash mr-1"></i>
                                delete</a>
                        </div>
                    </div>
                </td>
            </tr>


            {% endfor %}






        </tbody>
    </table>


    {% else %}




    <div class="card-content">
        <div class="card-body text-center bg-transparent miscellaneous">
            <img src="/static/bl/app-assets/images/pages/maintenance-2.png" class="img-fluid"
                alt="under maintenance" width="400">
            <h1 class="error-title my-1">No Media</h1>
            <p class="px-2">
                Seems a little quiet over here, upload something to share!
            </p>
            <a href={% url 'bl:uploadtype' %} class="btn btn-primary round glow mt-2">Upload now</a>
        </div>
    </div>


    {% endif %}
</div>
<!-- datatable ends -->
                    </div>
                    <div class="tab-pane" id="albums" aria-labelledby="albums-tab" role="tabpanel">
 {% if myalbums %}

   <table id="table-extended-chechbox" class="table table-transparent">

        <thead>
     
        </thead>
        <tbody>

            {% for album in myalbums  %}

            {% comment %} <tr>
              


                {% if album.cover %}
                <td class="text-bold-600 pl-0"><img src="{{album.cover}}" alt="file" class="mr-1" height="200"
                        width="200">
                    <a href={% url 'bl:uploaddetail' album.album_id %} >{{album.title}}</a>
                
                </td>
                {% else %}

                <td class="text-bold-600 pl-0"><img src="/static/bl/app-assets/images/album.png" alt="file"
                        class="mr-1" height="200" width="200">
                     <a href={% url 'bl:uploaddetail' album.album_id %} >{{album.title}}</a>
                    
                </td>
                {% endif %}




                <td>{{album.created_at}}</td>
            
                <td>
                    <div class="dropdown">
                        <span
                            class="bx bx-dots-horizontal-rounded font-medium-3 dropdown-toggle nav-hide-arrow cursor-pointer"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" role="menu">
                        </span>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a class="dropdown-item" href="#"><i class="bx bx-edit-alt mr-1"></i> edit</a>
                            <a class="dropdown-item" href="#"><i class="bx bx-trash mr-1"></i>
                                delete</a>
                        </div>
                    </div>
                </td>
            </tr> {% endcomment %}




            {% endfor %}






        </tbody>
    </table>

    {% else %}




    <div class="card-content">
        <div class="card-body text-center bg-transparent miscellaneous">
            <img src="/static/bl/app-assets/images/pages/maintenance-2.png" class="img-fluid"
                alt="under maintenance" width="400">
            <h1 class="error-title my-1">No Albums</h1>
            <p class="px-2">
                To share your albums, create and organize tracks that you have already uploaded
            </p>
            <a href={% url 'bl:uploadalbum' %} class="btn btn-primary round glow mt-2">Album Mode</a>
        </div>
    </div>


    {% endif %}
                    </div>
                    <div class="tab-pane" id="podcast" aria-labelledby="podcast-tab" role="tabpanel">

                    </div>

                    <div class="tab-pane" id="lyrics" aria-labelledby="lyrics-tab" role="tabpanel">

                    </div>


                </div>
            </div>
        </div>
    </div>
</section>












{% endblock content %}


{% block scripts %}










{% endblock scripts %}