bl/urls.py
from django.urls import path, include
from . import views
from django.conf.urls import url


app_name = 'bl'

urlpatterns = [
    path('', views.index, name="index"),
    path('submitRegister', views.submitRegister, name="submitRegister"),
    path('pending', views.pending, name="pending"),
    path('dashboard', views.dashboard, name="dashboard"),
    path('addsong', views.addsong, name="addsong"),
    path('addsongpage', views.addsongpage, name="addsongpage"),
    path('songdetail/<slug:id>', views.songdetail, name="songdetail"),
    path('uploads', views.uploads, name="uploads"),
    path('uploadtype', views.uploadtype, name="uploadtype"),
    path('uploadtrack', views.uploadtrack, name="uploadtrack"),
     path('submitAlbumDetail', views.submitAlbumDetail, name="submitAlbumDetail"),
    
    path('uploadalbum', views.uploadalbum, name="uploadalbum"),
    path('uploaddetail/<slug:id>', views.uploaddetail, name="uploaddetail"),


    

    path('index', views.index, name="index"),

    path('login', views.login, name="login"),

    path('registerbasicinfo', views.registerbasicinfo, name="registerbasicinfo"),

    path('changemailredirect', views.changemailredirect, name="changemailredirect"),

    path('loginredirect', views.loginredirect, name="loginredirect"),


    path('thanks', views.thanks, name="thanks"),

    path('mypod', views.mypod, name="mypod"),


    path('gettags', views.gettags, name="gettags"),

    path('uploadtag', views.uploadtag, name="uploadtag"),

    path('editUpload/<slug:track_id>', views.editUpload, name="editUpload"),
    path('editUploads', views.editUploads, name="editUploads"),

    path('editsong', views.editsong, name="editsong"),


path('editsongUpload', views.editsongUpload, name="editsongUpload"),




    path('myUploads', views.myUploads, name="myUploads"),



    



        path('register_view', views.register_view, name="register_view"),
    path('is_email_valid', views.is_email_valid, name="is_email_valid"),
                path('is_password_valid', views.is_password_valid, name="is_password_valid"),
                    path('is_username_valid', views.is_username_valid, name="is_username_valid"),



















    # SUDOURLS
    path('sudodashboard', views.sudodashboard, name="sudodashboard"),
    path('users', views.users, name="users"),
    path('userdetail/<slug:id>', views.userdetail, name="userdetail"),

    path('approvecreator/<slug:id>', views.approvecreator, name="approvecreator"),









    # path('expertDetail/<slug:id>', views.expertDetail , name="expertDetail"),
    # path('deleteExpert/<slug:id>', views.deleteExpert , name="deleteExpert"),
    path('register', views.register, name="register"),
    path('logout', views.logout, name="logout"),
    path('completeregister', views.completeregister, name="completeregister"),



    path('upload', views.upload, name="upload"),
    # url('oauth', include('social_django.urls', namespace='social')),

]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from rest_framework.routers import DefaultRouter
from django.conf.urls import url
router = DefaultRouter() 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('bl.urls')),
    path('rf', include(router.urls)),
    path('api/', include('api.urls')),
    path('doc/', include('rest_framework_docs.urls')),
    url('oauth', include('social_django.urls', namespace='social')),
     url(r'^notifications/', include('notify.urls', 'notifications')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bl/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from . models import *

from django.forms import ModelChoiceField,ModelForm,TextInput,Textarea


from django.db import transaction

from django.utils.translation import ugettext_lazy as _
import datetime


class FileFieldForm(forms.Form):
    ffile = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(max_length=30,
        widget=forms.TextInput(attrs={'class' : 'form-control','autocomplete':'off'}))
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'class' : 'form-control'}))
    first_name = forms.CharField(max_length=30,
        widget=forms.TextInput(attrs={'class' : 'form-control','autocomplete':'off'}))
    last_name = forms.CharField(max_length=30,
        widget=forms.TextInput(attrs={'class' : 'form-control','autocomplete':'off'}))
    phone = forms.CharField(max_length=30,
        widget=forms.TextInput(attrs={'class' : 'form-control','autocomplete':'off'})) 
    password1 = forms.CharField(max_length=30,
        widget=forms.TextInput(attrs={'class' : 'form-control','type' : 'password',}))   
    password2 = forms.CharField(max_length=30,
        widget=forms.TextInput(attrs={'class' : 'form-control','type' : 'password',}))  


    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('first_name','last_name','email','username')
        
    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        self.fields['email'].label = "Email Address"
        self.fields['password1'].label = "Password"
        self.fields['password2'].label = "Re-Type Password"
        self.fields['dob'].label = "Date of Birth"

    @transaction.atomic    
    def save(self):        
        user = super().save(commit=False)
        user.is_doctor = True
        

        user.save()    
        


        # user.role.set(range(Role.DOCTOR))     
        doctor = Doctor.objects.create(user=user)  
        Employee.objects.create(user=user)  
        # doctor.departmentname.add(*self.get('departmentname'))    
        # doctor.usericon.add(*self.get('usericon'))    
            
        return doctor

bl/views.py
from django.shortcuts import render,reverse,redirect,get_object_or_404
from django.http import HttpResponseRedirect
from . models import *
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from pyrebase import pyrebase
from django.contrib import auth
import re
from django.conf import settings
from django.urls import resolve
from django.http import JsonResponse
import sys
from django.core.files.base import ContentFile

from django.core.validators import validate_email
from django.core.exceptions import ValidationError
from django.conf import settings
import re



import base64

# Create your views here.

from tinytag import TinyTag
from notify.signals import notify
from django.contrib.auth.models import User


from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.template.loader import render_to_string
import requests


from .tokens import account_activation_token


config = {
    'apiKey': "AIzaSyANXTxEpF-3zzufKftR3_6AzhLXYh0tq6A",
    'authDomain': "pod-music-eb445.firebaseapp.com",
    'databaseURL':  "https://pod-music-eb445.firebaseio.com",
    'projectId': "pod-music-eb445",
    'storageBucket': "pod-music-eb445.appspot.com",
    'messagingSenderId': "866068650147",
    'appId' : "1:866068650147:web:3457f5499557ec4c"
 
}


firebase = pyrebase.initialize_app(config)
authe = firebase.auth()
db = firebase.database()



def logout(request):
    auth.logout(request)
    # if request.user.is_authenticated:
    #     auth.logout(request)
    # messages.add_message(request, messages.INFO,
    #                      'You are Successfully Logged Out')
    # messages.add_message(request, messages.INFO, 'Thanks for visiting.')
    return HttpResponseRedirect(reverse('bl:index'))

def login(request):
    return render(request,"bl/auth/login.html")


# @login_required
# def home(request):
    # print(request.user)
    
    # get_object_or_404(Creator, email=request.user.email)


    # try:
    #     if request.user.is_authenticated:
    #         creator = Creator.objects.get(email=request.user.email)
    #         if creator.status == 'pending_approval':
    #             return HttpResponseRedirect(reverse('bl:pending'))
    #             # return render(request,"bl/pending.html")
            
    #         elif creator.status == 'approved':
    #             return HttpResponseRedirect(reverse('bl:dashboard'))
    #             # return render(request,"bl/dashboard.html")

    #         else:
    #             return HttpResponseRedirect(reverse('bl:completeregister'))
    #     else:
    #         creator = None
    #         return HttpResponseRedirect(reverse('bl:index'))

    # except Creator.DoesNotExist:
    #     creator = None
    #     return HttpResponseRedirect(reverse('bl:index'))



    

def loginredirect(request):
    try:

        creator = Creator.objects.get(email=request.user.email)
        if creator.status == 'pending_approval':
            return HttpResponseRedirect(reverse('bl:pending'))
            # return render(request,"bl/pending.html")

        elif creator.status == 'inactive':
            return HttpResponseRedirect(reverse('bl:dashboard'))
            # return render(request,"bl/dashboard.html")
        elif creator.status == 'approved':
            return HttpResponseRedirect(reverse('bl:dashboard'))
            # return render(request,"bl/dashboard.html")

        elif creator.status == 'super_creator':
            return HttpResponseRedirect(reverse('bl:sudodashboard'))
        elif request.user.is_staff:
            return HttpResponseRedirect(reverse('bl:sudodashboard'))
            # return render(request,"bl/dashboard.html")
        else:
            return HttpResponseRedirect(reverse('bl:dashboard'))
            # return render(request,"bl/dashboard.html")






    except Creator.DoesNotExist:
        return HttpResponseRedirect(reverse('bl:registerbasicinfo'))

    return render(request,"bl/changemailredirect.html")



    # if creator is None:
    #     # creator = Creator(email=request.user.email,status="pending_approval")
    #     creator = Creator(email=request.user.email)
    #     creator.save()
    #     # messages.success(request, ' Your changes were successfully saved')

    #     return HttpResponseRedirect(reverse('bl:completeregister'))
    #     # return render(request,"bl/register-complete.html")



    


    





def changemailredirect(request):
    auth.logout(request)
    return render(request,"bl/registerX.html")  
    # return render(request,"bl/changemailredirect.html")

def registerbasicinfo(request):

    return render(request,"bl/auth/register-form.html")


# @login_required
def index(request):
    try:
        if not request.user.is_anonymous:
            
            creator = Creator.objects.get(email=request.user.email)
            if creator.status == 'pending_approval':
                # return HttpResponseRedirect(reverse('bl:pending'))
                return HttpResponseRedirect(reverse('bl:dashboard'))

            elif creator.status == 'inactive':
                return HttpResponseRedirect(reverse('bl:dashboard'))
                # return render(request,"bl/dashboard.html")
            elif creator.status == 'approved':
                return HttpResponseRedirect(reverse('bl:dashboard'))
                # return render(request,"bl/dashboard.html")

            elif creator.status == 'super_creator':
                return HttpResponseRedirect(reverse('bl:sudodashboard'))
            elif request.user.is_staff:
                return HttpResponseRedirect(reverse('bl:sudodashboard'))
                # return render(request,"bl/dashboard.html")
            else:
                return HttpResponseRedirect(reverse('bl:dashboard'))
                # return render(request,"bl/dashboard.html")

        else:
            return render(request,"bl/home.html")




    except Creator.DoesNotExist:
        return HttpResponseRedirect(reverse('bl:registerbasicinfo'))
        # return render(request,"bl/home.html")

def dashboard(request):
    creator = Creator.objects.get(username=request.user.username)
    context = {
        'creator': creator,
        'a' : 'active' 
    }

    # kwargs={'id1': request.POST.get('courseid'),
    # return HttpResponseRedirect(reverse('bl:completeregister'))
    return render(request,"bl/creator/dashboard.html",context)








def uploadtype(request):
    context = {
        'c' : 'active' 
    }

    return render(request,"bl/creator/upload-type.html",context)

def uploadtrack(request):
    context = {
        'c' : 'active' 
    }

    return render(request,"bl/creator/upload-track.html",context)

def uploadalbum(request):
    context = {
        'c' : 'active' 
    }

    return render(request,"bl/creator/upload-album-detail.html",context)







def sudodashboard(request):

    return render(request,"bl/admin/dashboard.html")

def users(request):
    creators = Creator.objects.all()
    context = {
        'creators': creators
    }
    print('Image Dta:  %s.' % creators)
    return render(request,"bl/admin/users.html",context)

def userdetail(request,id):
    creator = Creator.objects.get(pk=id)
    context = {
        'creator': creator
    }

    return render(request,"bl/admin/user-detail.html",context)

def approvecreator(request,id):
    creator = Creator.objects.get(pk=id)
    creator.status = "approved"
    creator.save()
    context = {
        'creator': creator
    }

    user = User.objects.get(username=creator.username)

    notify.send(request.user, recipient=user, actor=request.user, verb='Welcome to Pod for Creators', nf_type='followed_by_one_user')

    return HttpResponseRedirect(reverse('bl:userdetail', kwargs={'id':creator.id}))

    # return render(request,"bl/admin/user-detail.html",context)


def register(request):
    if request.user.is_authenticated:
        try:

            creator = Creator.objects.get(email=request.user.email)
            if creator.status == 'pending_approval':
                return HttpResponseRedirect(reverse('bl:pending'))
                # return render(request,"bl/pending.html")

            elif creator.status == 'inactive':
                return HttpResponseRedirect(reverse('bl:dashboard'))
                # return render(request,"bl/dashboard.html")
            elif creator.status == 'approved':
                return HttpResponseRedirect(reverse('bl:dashboard'))
                # return render(request,"bl/dashboard.html")

            elif creator.status == 'super_creator':
                return HttpResponseRedirect(reverse('bl:sudodashboard'))
                # return render(request,"bl/dashboard.html")
            else:
                return HttpResponseRedirect(reverse('bl:dashboard'))
                # return render(request,"bl/dashboard.html")







        except Creator.DoesNotExist:
           
            return HttpResponseRedirect(reverse('bl:registerbasicinfo'))
    else:
        return render(request,"bl/register.html")

def pending(request):

    return render(request,"bl/pending.html")

def uploads(request):
    myuploads = Track.objects.filter(uploaded_by=Creator.objects.get(username=request.user.username))
    myalbums = Album.objects.filter(uploaded_by=Creator.objects.get(username=request.user.username))
    print("hhh")
    print(myuploads)
    context = {
        'myuploads': myuploads,
        'myalbums':myalbums,
        'd' : 'active' 
    }
    return render(request,"bl/creator/uploads.html",context)





def uploaddetail(request,id):
    song = Track.objects.get(pk=id)
    # song_file = Upload.objects.get(upload_id=song.track_file)
    context = {
        'song': song,
         'd' : 'active' 
        # 'song_file':song_file
    }

  

bl/templates/bl/old/register-basic-info.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Element | Basik - Bootstrap 4 Web Application</title>
    <meta name="description" content="Responsive, Bootstrap, BS4">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1"><!-- style -->
    <link rel="stylesheet" href="/static/bl/assets/css/site.min.css">
</head>

<body>
        <header id="header" class="page-header p-2 bg-white">
            <div class="navbar navbar-expand-lg">
                <!-- brand --> <a href="index.html" class="navbar-brand"> 
                    <img src="/static/bl/assets/img/logo-light.png" alt="...">
                    <!-- <span class="hidden-folded d-inline l-s-n-1x">Basik</span> </a> -->
                    
                    <!-- / brand -->
                <!-- Navbar collapse -->
             
                <ul class="nav navbar-menu order-1 order-lg-2">
                    <li class="nav-item"><a class="nav-link no-ajax"
                            href="http://flatfull.com/themes/basik/docs/?hideAside=false">Guide</a></li>
                    <li class="d-flex align-items-center"><a href="http://themeforest.net/user/flatfull" target="_blank"
                            class="btn btn-rounded btn-sm btn-primary">Join</a></li><!-- Navarbar toggle btn -->
                    <li class="nav-item d-lg-none"><a href="#" class="nav-link px-2" data-toggle="collapse"
                            data-toggle-class data-target="#navbarToggler"><i data-feather="search"></i></a></li>
                </ul>
            </div>
        </header>
   
    <div id="main" class="layout-column flex">
       
        <!-- ############ Content START-->
        <div id="content" class="flex">
            <!-- ############ Main START-->
            <div>
                <div class="page-hero page-container" id="page-hero">
                    <div class="padding d-flex">
                        <div class="page-title">
                            <h2 class="text-md text-highlight">Complete Registration</h2><small class="text-muted">
                                your are submitting a join request with the email {{request.user.email}} <a href={% url 'bl:changemailredirect' %} class="text-primary">Change</a></small>
                        </div>
                        <div class="flex"></div>
                    
                    </div>
                </div>
                <div class="page-content page-container" id="page-content">
                    <div class="padding">
                        <div class="row">
                            <div class="col-md-12">

                                    <form data-plugin="parsley" method="post" enctype="multipart/form-data"  action={% url 'bl:submitRegister' %} data-option="{}">

                                            {% csrf_token %}  
                                <div class="card">
                                    <div class="card-header"><strong>Add Basic Info for Us to reach you easier</strong></div>
                                    <div class="card-body">
                                          


                                        <div class="input-group input-group-lg mb-3">
                                                <div class="input-group-prepend"><span class="input-group-text"
                                                        id="inputGroup-sizing-lg">Name</span></div>
                                                        
                                                        <input type="text" required name="artist_name"
                                                    class="form-control" aria-label="Name" placeholder="What should we call you"
                                                    aria-describedby="inputGroup-sizing-sm">
                                        </div>

                                        <div class="input-group input-group-lg mb-3">
                                                <div class="input-group-prepend"><span class="input-group-text"
                                                        id="inputGroup-sizing-lg">Contact Email</span></div>
                                                        
                                                        <input type="email" required name="contact_email"
                                                    class="form-control" aria-label="Name" placeholder="Email to keep in contact with you"
                                                    aria-describedby="inputGroup-sizing-sm">
                                        </div>


                                        <div class="input-group input-group-lg mb-3">
                                                <div class="input-group-prepend"><span class="input-group-text"
                                                        id="inputGroup-sizing-lg"> Phone (Optional)</span></div>
                                                        
                                                   


                                                    <input type="number" name="phone"
                                                    class="form-control" placeholder="XXX XXXX XXX" >
                                        </div>

                                        <div class="checkcard"><label class="ui-check"><input type="checkbox"
                                            name="check" checked="checked" required="true"><i></i> I agree
                                        to the <a href="#" class="text-primary">Terms of Service</a></label>
                                </div>
                                <div class="text-right"><button type="submit"
                                        class="btn btn-primary">Submit</button></div>
                                    </div>
                                </div>

                            </form>
                             
                            </div>
                           
                        </div>
                    </div>
                </div>
            </div><!-- ############ Main END-->
        </div><!-- ############ Content END-->
        <!-- ############ Footer START-->
        <div id="footer" class="page-footer hide">
            <div class="d-flex p-3"><span class="text-sm text-muted flex">&copy; Copyright. flatfull.com</span>
                <div class="text-sm text-muted">Version 1.1.2</div>
            </div>
        </div><!-- ############ Footer END-->
    </div>
    <script src="/static/bl/assets/js/site.min.js"></script>
</body>

</html>

bl/templates/bl/old/register-complete.html
Hello there, you are logged in with '{{request.user.email}}'
<br>
<a href={% url 'bl:logout' %}>Logout</a>

Artist Name
***Write a name that will be queried on submit and tell of name taken

Contact Email
***Use my logged in gmail
***Add another Email


Contact Phone
***we will call you


<form action={% url 'bl:submitRegister' %} method="post" enctype="multipart/form-data">  
    {% csrf_token %}  


Artist Name:<input name="artist_name" type="text" required> 

Contact Email: <input name="contact_email" type="email" required> 

Contact Phone:<input name="phone" type="text" required> 


<button type="submit">Save</button>

</form>

bl/templates/bl/old/songs.html
{% extends "bl/base.html" %}

{% block content %}

  <!-- ############ Content START-->
  <div id="content" class="flex">
    <!-- ############ Main START-->
    <div>
        <div class="page-hero page-container" id="page-hero">
            <div class="padding d-flex">
                <div class="page-title">
                    <h2 class="text-md text-highlight">My Tracks</h2><small class="text-muted">
                        All your pod tracks here
                    </small>
                </div>
                <div class="flex"></div>
             
            </div>
        </div>
        <div class="page-content page-container" id="page-content">
            <div class="padding">
                <div class="table-responsive">
                    <table id="datatable" class="table table-theme table-row v-middle" data-plugin="dataTable">
                        <thead>
                            <tr>
                                <th><span class="text-muted">ID</span></th>
                                <th><span class="text-muted">Cover Art</span></th>
                                <th><span class="text-muted">Title</span></th>
                                <th><span class="text-muted d-none d-sm-block">Plays</span></th>
                                <th><span class="text-muted d-none d-sm-block">Favorites</span></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                          
                            {% for song in mysongs  %}
                            <tr class="" data-id="1">
                                <td style="min-width:30px;text-align:center"><small class="text-muted">1</small>
                                </td>
                                <td><a href="#"><span class="w-32 avatar gd-primary"><img
                                                src="../assets/img/a1.jpg" alt="."></span></a></td>
                                <td class="flex"><a href="#" class="item-title text-color">
                                        {{ song.title }}   
                                </a>
                                    <div class="item-except text-muted text-sm h-1x">
                                        <!-- Description -->

                                    </div>
                                </td>
                                <td><span class="item-amount d-none d-sm-block text-sm">210</span></td>
                                <td><span class="item-amount d-none d-sm-block text-sm [object Object]">5</span>
                                </td>
                                <td>
                                    <div class="item-action dropdown"><a href="#" data-toggle="dropdown"
                                            class="text-muted"><i data-feather="more-vertical"></i></a>
                                        <div class="dropdown-menu dropdown-menu-right bg-black" role="menu"><a
                                                class="dropdown-item" href="#">See detail </a><a
                                                class="dropdown-item download">Download </a><a
                                                class="dropdown-item edit">Edit</a>
                                            <div class="dropdown-divider"></div><a
                                                class="dropdown-item trash">Delete item</a>
                                        </div>
                                    </div>
                                </td>
                            </tr>

                            {% endfor %}
                       
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div><!-- ############ Main END-->
</div><!-- ############ Content END-->


{% endblock content %}